import Link from "next/link";
import { Play, Activity, Code2, LineChart, MessageSquare, Search, Target, Users } from "lucide-react";

export default function Home() {
  const demos = [
    {
      id: "lead_scoring",
      title: "Lead Conversion Scorer",
      description: "Classify incoming leads by conversion probability using a trained Random Forest model.",
      icon: Target,
      metrics: "85.0% Accuracy • 0.933 ROC AUC",
      badge: "Classification"
    },
    {
      id: "investor_cluster",
      title: "Investor Persona Clustering",
      description: "Segment behavioral profile inputs into 4 distinct persona clusters using K-Means clustering.",
      icon: Users,
      metrics: "4 Segments • 0.395 Silhouette",
      badge: "Unsupervised"
    },
    {
      id: "sentiment",
      title: "Market News Sentiment",
      description: "Classify financial news headlines into Positive, Negative, or Neutral with SBERT embeddings.",
      icon: MessageSquare,
      metrics: "71.6% Accuracy • 0.689 F1",
      badge: "NLP Classification"
    },
    {
      id: "semantic_search",
      title: "Semantic Fund Search",
      description: "Match unstructured investor search terms to fund profiles using Sentence-BERT cosine similarity.",
      icon: Search,
      metrics: "< 120ms Latency • Top-5 Match",
      badge: "Semantic Engine"
    },
    {
      id: "nav_forecast",
      title: "NAV Time-Series Forecast",
      description: "Interactive historical holdout performance plot generated by a PyTorch LSTM network.",
      icon: LineChart,
      metrics: "89% R² Variance • 0.0152 MSE",
      badge: "Deep Learning"
    }
  ];

  return (
    <div className="flex flex-col gap-12 py-6">
      {/* Hero Section */}
      <section className="glass-card hero-bg accent-glow p-8 sm:p-12 md:p-16 flex flex-col items-center text-center gap-6 border-[var(--border-subtle)]">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[var(--accent-mint-dim)] border border-[var(--accent-mint)]/20 text-xs font-semibold text-[var(--accent-mint)] tracking-wider uppercase">
          AI Sandbox Demo — No Login Required
        </div>
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight max-w-4xl leading-tight">
          Mutual Fund Intelligence powered by <span className="gradient-text">Lume AI</span>
        </h1>
        <p className="text-slate-300 text-lg max-w-2xl leading-relaxed">
          An MVP sandbox illustrating offline-trained machine learning and deep learning models. Interact with live inference systems for lead scoring, behavioral clustering, sentiment analysis, semantic indexing, and NAV sequence forecasting — all powered by real, open-source evaluations.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-4 mt-2">
          <Link href="/demo" className="btn-primary flex items-center gap-2">
            <Play className="h-4 w-4" /> Try the Models Live
          </Link>
          <Link href="/insights" className="btn-secondary flex items-center gap-2">
            <Activity className="h-4 w-4" /> View Model Performance
          </Link>
        </div>
      </section>

      {/* Grid of Interactive Modules */}
      <section className="space-y-6">
        <div className="flex flex-col gap-2">
          <h2 className="text-2xl font-bold tracking-tight text-slate-100">Sandbox Interactive Demos</h2>
          <p className="text-slate-400 text-sm">Select any module below to evaluate the model live with custom or pre-filled dataset features.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {demos.map((demo) => {
            const Icon = demo.icon;
            return (
              <div key={demo.id} className="glass-card p-6 flex flex-col justify-between gap-6 border-[var(--border-subtle)]">
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-slate-800/80 border border-slate-700/50 text-[var(--accent-mint)]">
                      <Icon className="h-5 w-5" />
                    </div>
                    <span className="text-[10px] font-semibold tracking-wider text-slate-400 uppercase bg-slate-800/50 px-2 py-0.5 rounded border border-slate-700/30">
                      {demo.badge}
                    </span>
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-lg font-bold text-slate-200">{demo.title}</h3>
                    <p className="text-slate-400 text-sm leading-relaxed">{demo.description}</p>
                  </div>
                </div>

                <div className="space-y-3 pt-2 border-t border-[var(--border-subtle)]/50">
                  <div className="text-xs text-slate-500 font-medium">{demo.metrics}</div>
                  <Link
                    href={`/demo?task=${demo.id}`}
                    className="flex items-center justify-center gap-1.5 w-full py-2 rounded-lg text-xs font-semibold bg-slate-850 hover:bg-slate-800 border border-slate-700/60 text-slate-300 hover:text-slate-100 transition-all"
                  >
                    Open Live Sandbox <Play className="h-3 w-3" />
                  </Link>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* Summary Architecture Link Block */}
      <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-card p-6 border-[var(--border-subtle)] md:col-span-2 flex flex-col justify-between gap-4">
          <div className="space-y-2">
            <h3 className="text-lg font-bold text-slate-200">How Lume AI Works</h3>
            <p className="text-slate-400 text-sm leading-relaxed">
              Lume AI combines an offline Big Data pipeline (Pyspark ETL) with a modular inference engine. Data assets are cleaned, models are fit locally, and metrics are frozen directly from pipeline outcomes to prevent drift and preserve deterministic accuracy.
            </p>
          </div>
          <Link href="/about" className="inline-flex items-center gap-1 text-sm font-semibold text-[var(--accent-mint)] hover:underline">
            Explore the Architecture <Code2 className="h-4 w-4" />
          </Link>
        </div>

        <div className="glass-card p-6 border-[var(--border-subtle)] flex flex-col justify-between gap-4 bg-slate-900/30">
          <div className="space-y-2">
            <h3 className="text-lg font-bold text-slate-200">Github Repository</h3>
            <p className="text-slate-400 text-sm leading-relaxed">
              Access the complete pipeline training scripts, source files, and dataset assets on GitHub.
            </p>
          </div>
          <a
            href="https://github.com/snehadpatel"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2 w-full py-2.5 rounded-lg text-sm font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-slate-100 transition-all border border-slate-700"
          >
            GitHub Project
          </a>
        </div>
      </section>
    </div>
  );
}
